<html>

<head> Exception Handling</br></head>

<body>
    <script>
        try {
            var a = ["34", "32", "5", "31", "24", "44", "67"];
            throw new Error("this is an example for error")
        console.log(a)
        console.log(b)
        } catch (e) {
            console.log(e)
        }  finally{
            console.log("This is a finally block")
        }




    </script>
</body>

</html>